apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: sd3v97lq6-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-6d79b041ed.puy2.p3.openshiftapps.com/rhtap/rhtap-qe:c66f5120168f2380db5fea0ca72bfb687e5fc095@sha256:f25f05b40e33c7e9ab63b4c0e27289ac514ccd0484d07eb6cbc35262977fe368
          name: container-image
